Adptds-XX: Pre-Sprint 07 fix
kyperbelt/adapted-strength pull request #61
Opened 2024-02-27 21:48 UTC by CaseyCubed

### Description
Created hamburger menu

### Solution
Improved navbar implementation in navBar.jsx menu. Navigation menu is now a hamburger style menu located on top right of screen (locked), and will toggle a menu that slides from the right.

### Testing
All links are functional as before, and any links previously on the navbar have been migrated over to the new menu type.

2024-03-01 03:20 UTC, kyperbelt requested changes
Hey Casey, I Checked it out, Great Work!

The only thing is, can we make the button darker. It doesn't show up very well on my screen. I think just changing the color to black might help. 

I left a comment on the div that requires the z-50 for it to fix the overlapping thing.

2024-03-01 03:20 UTC, kyperbelt commented on frontend/adapted_strength-app/src/components/navBar.jsx
> +    <div>
put z-50 on this bad boy

2024-03-05 19:58 UTC, CaseyCubed reviewed
@kyperbelt Thanks for suggestion. z-50 has been inputted and it worked. Don't know why I didn't try this sooner.

2024-03-06 05:43 UTC, kyperbelt approved these changes

2024-03-06 05:43 UTC, merged